Reformulação do checks-py
splor-mg/checks pull request #3
Opened 2024-04-25 19:33 UTC by labanca

- Setup inicial do pacote
- Strings de descrição do pacote provavelmente precisam ser modificadas
- Instalação via pip ainda com erros (ver issue #2)
-

2024-04-29 21:00 UTC, fjuniorr commented
Incluir teste unitário para função `parse_requirements`

2024-05-07 22:01 UTC, labanca commented
> Incluir teste unitário para função `parse_requirements`.
Teste unitário criado.

Erros descobertos em função do teste:
- check-packages não tratava dependências com extras, mas sem versão específica.
- espaços são permitidos dentro das depedências no arquivo requirements, mas não eram tratados pelo check-packages.

2024-05-07 22:01 UTC, labanca commented
@fjuniorr favor revisar quando possível.

2024-05-14 18:12 UTC, fjuniorr requested changes
Eu ia reclamar da ordem que você escreveu as funções em `src/checks/requirements.py` mas descobri que você está tecnicamente certo!

A recomendação da [The Stepdown Rule](https://dzone.com/articles/the-stepdown-rule) é escrever as funções com maior nível de abstração no inicio do módulo, e não no final. 

Eu nunca faço isso!

2024-05-14 18:12 UTC, fjuniorr commented on tests/unit/test_parse_requirements.py
> +test_parse_requirement()
Não precisa de fazer essa chamada direta. Ao rodar `pytest` na linha de comando todos os os testes serão coletados e executados.

2024-05-14 18:12 UTC, fjuniorr commented on tests/unit/test_parse_requirements.py
> +    result = {package: version for dep in input for package, version in parse_requirement(dep).items()}
Pra esse caso fazer uma escrita direta pro teste de cada linha deixa o código mais simples de entender (pode escrever múltiplas assertions no mesmo teste):

```python
assert parse_requirement('pandas') == {"pandas": None}
```

2024-05-14 18:12 UTC, fjuniorr commented on src/checks/requirements.py
Talvez vale a pena ser mais verboso e alterar o nome da função para `check_installed_packages`.

Sobre os argumentos, vamos [padronizar](https://github.com/splor-mg/checks-planejamento/issues/4#issuecomment-1805646914) em um único `stop_on_failure` que vale para o check como um todo.

2024-05-14 18:12 UTC, fjuniorr commented on src/checks/cli.py
> +@app.command("check-packages")
Não sei se a gente vai ter uso muito uso pra testes via interface CLI, mas se a gente for usar acho que fica mais bonito se a gente chamar somente o nome do teste sem o prefixo (que de certa forma já está no nome do pacote). Ou seja:

```bash
checks installed-packages requirements.in
```

Será que a vale a pena mudar o nome do `[project.scripts]` pra `check` pra ficar

```bash
check installed-packages requirements.in
```

2024-05-20 16:14 UTC, labanca commented on src/checks/requirements.py
Dexei o valor default do  `stop-on-failure` como False. Mater dessa forma?

2024-05-21 16:14 UTC, fjuniorr commented on src/checks/requirements.py
Ou, pra esse check acho que o default tem que ser `stop-on-failure`

2024-05-22 11:16 UTC, fjuniorr commented on src/checks/requirements.py
Putz, parei a frase na metade. Mas era `stop-on-failure` igual a True mesmo!

2024-05-22 11:17 UTC, fjuniorr approved these changes

2024-05-22 12:54 UTC, labanca commented
O caso levantando na útlima reunião pelo Henrique não gerou erros nos testes. 

```
assert parse_requirement('frictionless[excel,pandas]') == {'frictionless': None}
assert parse_requirement('frictionless[excel,pandas]==1.1.3') == {'frictionless': '1.1.3'}
```

Ambas situações funcionaram sem problemas.

2024-05-22 17:17 UTC, merged